apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-python-app-devops
  namespace: argocd
  labels:
    app.kubernetes.io/name: simple-python-app-devops
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BaruchiHalamish20/simple-python-app-devops
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
